apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: '9100'
    prometheus.io/path: /metrics
  name: node-exporter
  namespace: monitoring
spec:
#  type: NodePort
  ports:
  - name: https
    port: 9100
    targetPort: https
#    nodePort: 31010
  selector:
    app: node-exporter
